config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :competitions
  resources :round_video_ratings
  resources :round_videos
  resources :round_tasks
  resources :comments
  resources :round_users
  resources :rounds
  resources :types

  get '/rounds/type/:type_id' => 'rounds#show_of_type', as: :show_of_type
  get '/round_videos/list/:round_id' => 'round_videos#list', as: :round_video_list
  get '/rounds/rating/:round_id' => 'round_videos#rating', as: :rating_round_video
  get '/categories' => 'types#block_list', as: :categories
  get '/ratings/:type_id' => 'round_video_ratings#list', as: :ratings
  get '/archive' => 'rounds#archive', as: :archive
  get '/archive/:round_id' => 'rounds#archive_round', as: :archive_round

  get '/round_users_payment' => 'round_users#payment'
  post '/round_users_payment' => 'round_users#payment'

  get '/how_to' => 'help#how_to', as: :how_to
  get '/about' => 'help#about', as: :about
  get '/contacts' => 'help#contacts', as: :contacts
  get '/download_reglament' => 'help#download_reglament', as: :download_reglament

  get '/admin' => 'help#admin_panel', as: :admin_panel
  get '/prize' => 'help#prize_panel', as: :prize_panel
  get '/users' => 'help#user_list', as: :user_list

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root "types#block_list"

  get '/image_crop' => 'help#image_crop', as: :image_crop
  get '/avatar_with_frame' => 'help#avatar_with_frame', as: :avatar_with_frame
  get '/avatar_with_frame_download' => 'help#avatar_with_frame_download', as: :avatar_with_frame_download

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_action :admin_required!, only: [:admin_panel, :prize_panel, :user_list]

  # require 'rubygems'
  require 'RMagick'
  include Magick

  def about
  end

  def how_to
  end

  def download_reglament
    send_file ("public/zaruba-reglament.docx"), :type=>"application/vnd.openxmlformats-officedocument.wordprocessingml.document", :x_sendfile=>true
  end

  def contacts
  end

  def admin_panel
  end

  def prize_panel
  end

  def user_list
    @users = User.all.order(created_at: :asc)

    @last_month_users_count = @users.select{ |u| u.created_at >= Date.today.at_beginning_of_month }.count
  end

  def image_crop
    frame = Image.read('public/frame.png')[0]
    avatar = Image.read('public/avatar.png')[0]
    frame = frame.adaptive_resize(avatar.columns, avatar.rows)
    # avatar = avatar.adaptive_resize(600, 600)
    avatar = avatar.crop((avatar.columns - (avatar.rows.to_f * 4/5)) / 2, 0, (avatar.rows.to_f * 4/5), avatar.rows)
    frame = frame.adaptive_resize(avatar.columns, avatar.rows)
    combined = avatar.composite(frame, Magick::EastGravity, 0, 0, Magick::OverCompositeOp) #the 0,0 is the x,y
    combined.format = 'png'
    send_data combined.to_blob, :stream => 'false', :filename => 'zaruba_avatar.png', :type => 'image/png', :disposition => 'inline'

    # processed_image = StringIO.open(trimmed_img.to_blob)
  end

  def image_test_work
    frame = Image.read('public/frame.png')[0]
    avatar = Image.read('public/avatar.png')[0]
    avatar = avatar.adaptive_resize(636, 578)
    combined = frame.composite(avatar, Magick::EastGravity, 272, -76, Magick::OverCompositeOp) #the 0,0 is the x,y
    combined.format = 'png'
    send_data combined.to_blob, :stream => 'false', :filename => 'zaruba_avatar.png', :type => 'image/png', :disposition => 'inline'
  end

  def avatar_with_frame
    frame = Image.read('public/frame.png')[0]

    begin
      if current_user.avatar.url.include? "missing_avatar"
        avatar = Image.read('public/' + 'missing_avatar.png')[0]
      else
        avatar = Image.read('public' + current_user.avatar.url(:medium).split('?')[0])[0]
      end
    rescue => ex
      avatar = Image.read('public/' + 'missing_avatar.png')[0]
    end

    frame = frame.adaptive_resize(avatar.columns, avatar.rows)
    combined = avatar.composite(frame, Magick::EastGravity, 0, 0, Magick::OverCompositeOp) #the 0,0 is the x,y
    combined.format = 'png'
    send_data combined.to_blob, :stream => 'false', :filename => 'zaruba_avatar.png', :type => 'image/png', :disposition => 'inline'
  end

  def avatar_with_frame_download
    cookies.permanent[:avatar_downloaded] = "true"

    frame = Image.read('public/frame.png')[0]

    begin
      if current_user.avatar.url.include? "missing_avatar"
        avatar = Image.read('public/' + 'missing_avatar.png')[0]
      else
        avatar = Image.read('public' + current_user.avatar.url(:medium).split('?')[0])[0]
      end
    rescue => ex
      avatar = Image.read('public/' + 'missing_avatar.png')[0]
    end

    frame = frame.adaptive_resize(avatar.columns, avatar.rows)
    combined = avatar.composite(frame, Magick::EastGravity, 0, 0, Magick::OverCompositeOp) #the 0,0 is the x,y
    combined.format = 'png'
    send_data combined.to_blob, :filename => 'zaruba_avatar.png', :disposition => 'attachment'
  end

end

app/helpers/help_helper.rb
module HelpHelper
end

app/views/help/_video_capturing.html.slim
.spoiler-block
  button.btn.btn-primary.info-spoiler-btn СТАНДАРТЫ ВИДЕОСЪЕМКИ КОМПЛЕКСА
  .info-spoiler
    br
    p
      | Прежде, чем участник приступит к выполнению задания, нужно представиться, разборчиво назвав фамилию и имя, категорию, в которой выступает атлет, а должен назвать категорию и комплекс. Продемонстрировать используемый в задании инвентарь необходимо перед выполнением задания.

    p
      | В случае использования стандартных дисков и грифа, продемонстрировать маркировку, так, чтобы ее было четко видно в кадре. В случае отсутствия маркировки, продемонстрировать в кадре процесс взвешивания всех элементов в отдельности или штанги целиком, так чтобы показания весов были хорошо видны в кадре.

    p
      | В случае использования стандартного набивного мяча, продемонстрировать маркировку, так, чтобы ее было четко видно в кадре. В случае отсутствия маркировки, продемонстрировать в кадре процесс взвешивания мяча, так чтобы показания весов были хорошо видны в кадре.

    p
      | Также необходимо продемонстрировать процесс измерения высоты метки для бросков мяча.

    p
      | Видео должно быть не редактировано и не обрезано.

    p
      | Рекомендуется присутствие в кадре человека, осуществляющий подсчет повторений. Также на протяжении всего задания в кадре должен быть виден секундомер, а его показания быть различимы без затруднений.

    p
      | Видео необходимо записывать с ракурса, не затрудняющего оценку выполнения стандартов движений.

    p
      | Видео должно быть загружено на видеохостинг youtube.com и находиться в публичном доступе. Видео, загруженное на иные хостинги, кроме youtube.com, рассматриваться не будет. Ответственностью атлета является предоставление открытого доступа к просмотру видео.

    p
      | Название видео должно содержать: фамилию и имя участника, название комплекса и категорию, в которой он выступает.

app/views/help/about.html.slim
legend
  h2
    | О проекте

p
  strong> Онлайн-Zаруба
  | - Новая турнирная площадка для спортивных состязаний и возможности для лучших заработать деньги. Здесь нет ограничения по виду спорта, возрасту или месту проживания, участие может принять каждый.Мы предлагаем каждому попробовать свои силы и “зарубиться” с соперниками по всему миру. Докажи что ты лучший и получи награду. Мы учли опыт всех подобных соревнований, собрали все лучшее и сформировали самый интересный, на наш взгляд, турнир. В этом может убедиться каждый.

app/views/help/admin_panel.html.slim
legend
  h2
    | Панель Судьи


= link_to "Оценка видео", round_video_list_path(0), class: "btn btn-block btn-primary"
= link_to "Управление соревнованиями", competitions_path, class: "btn btn-block btn-primary"
= link_to "Управление комплексами", rounds_path, class: "btn btn-block btn-primary"
= link_to "Управление категориями", types_path, class: "btn btn-block btn-primary"
= link_to "Список пользователей", user_list_path, class: "btn btn-block btn-primary"
= link_to "Реклама/Партнеры", ads_path, class: "btn btn-block btn-primary"

app/views/help/contacts.html.slim
legend
  h2
    | Контакты

p
  strong> Чемерисова Елена Юрьевна
  | - руководитель проекта
  br
  | elenagyseva88@mail.ru

  br
  br

  strong> Чемерисов Владлен Жанович
  | - исполнительный директор ( по вопросам развития, рекламы, сотрудничества)
  br
  | http://vk.com/id11174765

  br
  | chemerisov_vlad@mail.ru

  br
  br

  strong> Фазлиахметов Амир Динарович
  | - администратор (технические вопросы)
  br
  | http://vk.com/id257238993
  br
  | zaruba.help@gmail.com

app/views/help/how_to.html.slim
legend
  h2
    | Как принять участие

ol.how-to-list
  li Зарегистрируйся. Выложи фото своего профиля на стене VK или в Instagram.
  li Выбери категорию, оплати участие.
  li До завершения таймер (7 дней) сними и отправь видео выполненного комплекса на YouTube в открытом доступе, указав в названии CrossFit Zаруба <<Деньги за победу>> "Группа" "ФИО" и и результат комплекса (время и количество повторений). Важно указать все правильно!
  li Ссылку на видео с YouTube отправить на сайт с помощью специальной формы. По истечению таймера (7 дней) будет определен потенциальный победитель. Затем, только для участников, есть возможность улучшить результат комплекса в течение 3х дней и стать победителем!
  li Победителю будет выслан призовой фонд категории на указанные банковские реквизиты.

= link_to "#{fa_icon 'download'} Скачать регламент".html_safe, download_reglament_path, class: "btn btn-primary"

hr

= render '/help/video_capturing'

app/views/help/user_list.html.slim
legend
  h2
    | Пользователи

table.table
  tr
    thead
      th ID
      th Имя
      th Фамилия
      th Email
      th Телефон
    tbody
      - @users.each do |user|
        tr
          td=user.id
          td=user.fname
          td=user.lname
          td=user.email
          td=user.phone