config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :competitions
  resources :round_video_ratings
  resources :round_videos
  resources :round_tasks
  resources :comments
  resources :round_users
  resources :rounds
  resources :types

  get '/rounds/type/:type_id' => 'rounds#show_of_type', as: :show_of_type
  get '/round_videos/list/:round_id' => 'round_videos#list', as: :round_video_list
  get '/rounds/rating/:round_id' => 'round_videos#rating', as: :rating_round_video
  get '/categories' => 'types#block_list', as: :categories
  get '/ratings/:type_id' => 'round_video_ratings#list', as: :ratings
  get '/archive' => 'rounds#archive', as: :archive
  get '/archive/:round_id' => 'rounds#archive_round', as: :archive_round

  get '/round_users_payment' => 'round_users#payment'
  post '/round_users_payment' => 'round_users#payment'

  get '/how_to' => 'help#how_to', as: :how_to
  get '/about' => 'help#about', as: :about
  get '/contacts' => 'help#contacts', as: :contacts
  get '/download_reglament' => 'help#download_reglament', as: :download_reglament

  get '/admin' => 'help#admin_panel', as: :admin_panel
  get '/prize' => 'help#prize_panel', as: :prize_panel
  get '/users' => 'help#user_list', as: :user_list

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root "types#block_list"

  get '/image_crop' => 'help#image_crop', as: :image_crop
  get '/avatar_with_frame' => 'help#avatar_with_frame', as: :avatar_with_frame
  get '/avatar_with_frame_download' => 'help#avatar_with_frame_download', as: :avatar_with_frame_download

end

app/models/round_video.rb
class RoundVideo < ActiveRecord::Base
  belongs_to :round_user
  has_one :round_video_rating, :dependent => :delete
end

app/controllers/round_videos_controller.rb
class RoundVideosController < ApplicationController
  before_action :set_round_video, only: [:show, :edit, :update, :destroy]
  before_action :admin_required!, except: [:show, :create]

  # GET /round_videos
  # GET /round_videos.json
  def index
    @round_videos = RoundVideo.order(created_at: :desc, is_checked: :asc).select { |rv| rv.round_user != nil }

    # abort(@round_videos.inspect)
  end

  def list
    @round_id = params[:round_id]
    if @round_id && @round_id != '0' && @round_id != '00'
      @round_videos =  RoundVideo.order(created_at: :desc, is_checked: :asc).joins(:round_user).where(round_users: {round_id: @round_id})
      @round_id = @round_video.nil? || @round_video.first.nil? ? @round_id.sub(/^0/, "").to_i : @round_video.first.round_user.round_id
    else
      @round_videos = RoundVideo.order(created_at: :desc, is_checked: :asc).select { |rv| rv.round_user != nil }
      @round_id = 0;
    end

    @rounds = Round.all

    # abort(@round_videos)
  end

  # GET /round_videos/1
  # GET /round_videos/1.json
  def show
  end

  # GET /round_videos/new
  def new
    @round_video = RoundVideo.new
  end

  # GET /round_videos/1/edit
  def edit
  end

  def rating
    @round_video = RoundVideo.find(params[:round_id])
    @round_video_rating = @round_video.round_video_rating
    @round_video_rating ||= RoundVideoRating.new(round_video_id: @round_video.id)
  end

  # POST /round_videos
  # POST /round_videos.json
  def create
    @round_video = RoundVideo.new(round_video_params)
    # @round_video.user_id = current_user.id unless current_user.is_admin?

    round_user = @round_video.round_user

    if round_user.available == 0
      return redirect_to show_of_type_path(@round_video.round_user.round.type_id)
    end

    round_user.available -= 1
    round_user.save

    round = @round_video.round_user.round

    if round.rating_type == 0
      @round_video.minutes = round.minutes
      @round_video.seconds = round.seconds
    elsif round.rating_type == 1
      @round_video.repeats = round.repeats
    end

    respond_to do |format|
      if @round_video.save
        format.html { redirect_to show_of_type_path(@round_video.round_user.round.type_id), notice: "Видео было успешно отправлено!" }
        format.json { render :show, status: :created, location: @round_video }
      else
        format.html { redirect_to show_of_type_path(@round_video.round_user.round.type_id) }
        format.json { render json: @round_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /round_videos/1
  # PATCH/PUT /round_videos/1.json
  def update
    respond_to do |format|
      if @round_video.update(round_video_params)
        format.html { redirect_to round_video_list_path(0), notice: 'Round video was successfully updated.' }
        format.json { render :show, status: :ok, location: @round_video }
      else
        format.html { redirect_to round_video_list_path(0), notice: 'Round video was unsuccessfully updated.' }
        format.json { render json: @round_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /round_videos/1
  # DELETE /round_videos/1.json
  def destroy
    @round_video.destroy
    respond_to do |format|
      format.html { redirect_to round_video_list_path(0), notice: 'Round video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round_video
      @round_video = RoundVideo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_video_params
      params.require(:round_video).permit(:round_user_id, :youtube_url, :minutes, :seconds, :repeats, :is_checked)
    end
end

app/helpers/round_videos_helper.rb
module RoundVideosHelper
end

app/views/round_videos/_form.html.slim
= form_for @round_video, html: { class: "form form-horizontal round_video" } do |f|
  .form-group
    = f.label :round_user_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select(:round_user_id, RoundUser.all.order(created_at: :desc).map { |ru| ["#{ru.id}: #{ru.round.title}, #{ru.user.email}", ru.id]}, {}, class: "form-control")
      / = f.text_field :round_user_id, :class => 'form-control'
    = f.error_span(:round_user_id)
  .form-group
    = f.label :youtube_url, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :youtube_url, :class => 'form-control'
    = f.error_span(:youtube_url)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), round_videos_path, :class => 'btn'

app/views/round_videos/edit.html.slim
- model_class = RoundVideo
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/round_videos/index.html.slim
- model_class = RoundVideo
.page-header
  h1 Видео участников
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th Пользователь
      th Повторения
      th Время
      th Статус
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @round_videos.each do |round_video|
      tr
        td= link_to round_video.id, round_video_path(round_video)
        td= "#{round_video.round_user_id}: #{round_video.round_user.user.email}"
        - if round_video
          td= round_video.repeats
          td
            = "#{round_video.minutes}:#{round_video.seconds}"
        - else
          td Не оценено
          td Не оценено
        td= round_video.is_checked ? "Проверено" : "-"
        td
          = link_to "Оценить", rating_round_video_path(round_video), class: 'btn btn-primary btn-xs'
          '
          / = link_to t('.edit', :default => t("helpers.links.edit")), edit_round_video_path(round_video), :class => 'btn btn-default btn-xs'
          / '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), round_video_path(round_video), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), new_round_video_path, :class => 'btn btn-primary'

app/views/round_videos/list.html.slim
- model_class = RoundVideo
.page-header
  h1 Видео участников

.select-round-id
  | Комплекс:
  =<> select_tag('round_round_id', options_for_select( ([["Все комплексы", 0]] + @rounds.collect { |r| ["#{r.competition ? r.competition.title : ''}: #{r.title}", r.id]}), selected: @round_id ), class: "")
  javascript:
    $('#round_round_id').on('change', function(){
      var round_id = $('#round_round_id').val();
      window.location.href = "#{round_video_list_path(0)}" + round_id;
    });
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th Пользователь
      th Повторения
      th Время
      th Статус
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @round_videos.each do |round_video|
      tr
        td= link_to round_video.id, round_video_path(round_video)
        td= "#{round_video.round_user_id}: #{round_video.round_user.user.email}"
        - if round_video
          td= round_video.repeats
          td
            = "#{round_video.minutes}:#{round_video.seconds}"
        - else
          td Не оценено
          td Не оценено
        td= round_video.is_checked ? "Проверено" : "-"
        td
          = link_to "Оценить", rating_round_video_path(round_video), class: 'btn btn-primary btn-xs'
          '
          / = link_to t('.edit', :default => t("helpers.links.edit")), edit_round_video_path(round_video), :class => 'btn btn-default btn-xs'
          / '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), round_video_path(round_video), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), new_round_video_path, :class => 'btn btn-primary'

app/views/round_videos/new.html.slim
- model_class = RoundVideo
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/round_videos/rating.html.slim
- model_class = RoundVideo
.page-header
  h1 Оценка видео

p
  strong Пользователь:
  br
  = @round_video.round_user.user.email
p
  strong Видео:
  br
    iframe[width="90%" height="350px" src="#{get_youtube_link(@round_video.youtube_url)}" frameborder="0"]

= form_for @round_video, html: { class: "form form-horizontal round_video" } do |f|
  = f.hidden_field :round_user_id, value: @round_video.round_user_id
  = f.hidden_field :youtube_url, value: @round_video.youtube_url

  .form-group.input-group
    span.input-group-addon Время(минуты)
    = f.text_field :minutes, :class => 'form-control', value: @round_video.minutes
  .form-group.input-group
    span.input-group-addon Время(секунды)
    = f.text_field :seconds, :class => 'form-control', value: @round_video.seconds
  .form-group.input-group
    span.input-group-addon Повторения
    = f.text_field :repeats, :class => 'form-control', value: @round_video.repeats
  .form-group
    .checkbox
      label
        = f.check_box :is_checked
        | Окончательно проверено судьей


  .form-group
    = f.submit "Оценить", :class => 'btn btn-primary'
    '
    = link_to "Назад", round_videos_path, :class => 'btn btn-default'


/ = form_for @round_video_rating, html: { class: "form form-horizontal round_video_rating" } do |f|
/   .form-group.hide
/       = f.hidden_field :round_video_id
/   .form-group.input-group
/     span.input-group-addon Повторения
/     = f.text_field :score, :class => 'form-control'
/   .form-group.input-group
/     span.input-group-addon Время(минуты)
/     = f.text_field :time, :class => 'form-control'
/   .form-group.input-group
/     span.input-group-addon Время(секунды)
/     = f.text_field :time, :class => 'form-control'
/   .form-group
/       = f.submit "Оценить", :class => 'btn btn-primary'
/       '
/       = link_to t('.back', :default => t("helpers.links.back")), round_videos_path, :class => 'btn btn-default'

app/views/round_videos/show.html.slim
- model_class = RoundVideo
.page-header
  h1 Видео

p
  strong Пользователь:
  br
  = @round_video.round_user.user.email
p
  strong Статус:
  br
  span[class="#{@round_video.is_checked ? 'text-success' : 'text-warning'}"]
    = @round_video.is_checked ? "Проверено" : "Проверяется"

p
  strong Повторения:
  br
  = @round_video.repeats

p
  strong Время:
  br
  = "#{@round_video.minutes}:#{@round_video.seconds}"

p
  strong Видео:
  br
    iframe[width="90%" height="350px" src="#{get_youtube_link(@round_video.youtube_url)}" frameborder="0"]

- if @round_video.round_user && @round_video.round_user.round
  = link_to t('.back', :default => t("helpers.links.back")), ratings_path(@round_video.round_user.round.type_id), :class => 'btn btn-default'