config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :competitions
  resources :round_video_ratings
  resources :round_videos
  resources :round_tasks
  resources :comments
  resources :round_users
  resources :rounds
  resources :types

  get '/rounds/type/:type_id' => 'rounds#show_of_type', as: :show_of_type
  get '/round_videos/list/:round_id' => 'round_videos#list', as: :round_video_list
  get '/rounds/rating/:round_id' => 'round_videos#rating', as: :rating_round_video
  get '/categories' => 'types#block_list', as: :categories
  get '/ratings/:type_id' => 'round_video_ratings#list', as: :ratings
  get '/archive' => 'rounds#archive', as: :archive
  get '/archive/:round_id' => 'rounds#archive_round', as: :archive_round

  get '/round_users_payment' => 'round_users#payment'
  post '/round_users_payment' => 'round_users#payment'

  get '/how_to' => 'help#how_to', as: :how_to
  get '/about' => 'help#about', as: :about
  get '/contacts' => 'help#contacts', as: :contacts
  get '/download_reglament' => 'help#download_reglament', as: :download_reglament

  get '/admin' => 'help#admin_panel', as: :admin_panel
  get '/prize' => 'help#prize_panel', as: :prize_panel
  get '/users' => 'help#user_list', as: :user_list

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root "types#block_list"

  get '/image_crop' => 'help#image_crop', as: :image_crop
  get '/avatar_with_frame' => 'help#avatar_with_frame', as: :avatar_with_frame
  get '/avatar_with_frame_download' => 'help#avatar_with_frame_download', as: :avatar_with_frame_download

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :type
  belongs_to :competition
  has_many :round_users, :dependent => :nullify
  has_many :comments, :dependent => :delete_all
  has_many :round_tasks, :dependent => :delete_all
  accepts_nested_attributes_for :round_tasks, reject_if: :all_blank, allow_destroy: true

  has_attached_file :image, styles: { high: "500x700>", medium: "300x450>", thumb: "100x170>" },
    default_url: ":style/missing_round_image.png"
    # url: "/system/rounds/:id/:style/:basename.:extension",
    # path: ":rails_root/public/system/rounds/:id/:style/:hash.:extension",
    # hash_secret: "longSecretString"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def prize
    prize = (self.start_prize + self.round_users.count * self.type.price * (self.prize_percent.to_f / 100)).round

    if self.peak_prize <= 0
      return prize
    else
      return [prize, self.peak_prize].min.round
    end
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]
  before_action :admin_required!, except: [:show_of_type, :archive, :archive_round]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all.order(id: :desc)
  end

  # GET /rounds/1
  # GET /rounds/1.json
  # def show
  # end

  # GET /rounds/types/1
  def show_of_type
    @need_round_types = true

    # abort((Time.now.end_of_day + 1.second).inspect)

    @competition = Competition.current
    return redirect_to root_path if @competition.nil?

    # @round = Round.where(type_id: params[:type_id]).first or not_found
    @round = @competition.rounds.select { |r| r.type_id.to_s == params[:type_id].to_s }.first

    return redirect_to root_path if @round.nil?

    # abort(@round.inspect)

    @round_users_count = RoundUser.where(round_id: @round.id).count
    @prize = @round.type.price * @round_users_count * 0.7
    # if @round_users_count == 1
    #   @prize = @round.type.price
    # else
    #   @prize = @round.type.price * @round_users_count * 0.7
    # end

    if current_user
      # @competition.round.each do |r|
      #   if r.type_id == 5
      # end
      @competition_user_rounds = current_user.round_users.joins(:round).where({rounds: { competition_id: @competition.id}})
      @team_round_registered = false
      @not_team_round_registered = false

      @team_category = Type.find_by_is_team(true)

      @competition_user_rounds.each do |cur|
        if !@team_category.nil? && cur.round.type_id == @team_category.id
          @team_round_registered = true
        else
          @not_team_round_registered = true
        end
      end

      @cant_register_team = @team_round_registered
      @cant_register_solo = @not_team_round_registered

      # abort(@cant_register.inspect)

      # @user_round_registered = !current_user.round_users.find_by(round_id: @round.id).blank?
      @round_user = current_user.round_users.find_by(round_id: @round.id)
      # @round_video_sent = !@round_user.round_videos.blank? if @round_user
      @round_video_sent = @round_user.available == 0 if @round_user
    end
    @comments = @round.comments
    @round_tasks = RoundTask.where(round_id: @round.id)

    @end_date = (@round.competition.start_date + @round.competition.days.days - 1.days).in_time_zone('Moscow').end_of_day

    # abort @end_date.inspect
    # abort Time.now.inspect

    if @end_date < Time.now

      if @round_user
        if @round_user.round_videos.select{|rv| rv.created_at < @end_date}.count == 0
          if @round_user.available - 1 > 0
            @can_send_video = true
          end
        elsif @round_user.available > 0
          @can_send_video = true
        end
      end

      @end_date = (@end_date + @round.competition.timer_days.days).in_time_zone('Moscow').end_of_day

      # abort @end_date.inspect

      @winner_user_enabled = true

      @round_videos = RoundVideo.joins(:round_user).where(is_checked: true, round_users: { round_id: @round.id })

      if @round.rating_type == 0
        @winner_round_video = @round_videos.order(repeats: :desc).first
      else
        @winner_round_video = @round_videos.order(minutes: :asc, seconds: :asc).first
      end
    end
  end

  def archive
    @rounds = Round.all.order(id: :desc)
  end

  def archive_round
    @archive_round = true
    @round = Round.find(params[:round_id])

    @round_users_count = RoundUser.where(round_id: @round.id).count
    if @round_users_count == 1
      @prize = @round.type.price
    else
      @prize = @round.type.price * @round_users_count * 0.7
    end

    @competition = Competition.current
    return redirect_to root_path if @competition.nil?

    @round_videos = RoundVideo.joins(:round_user).where(round_users: { round_id: @round.id }).order(repeats: :desc, minutes: :asc, seconds: :asc)
    @winner_round_video = @round_videos.first
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to rounds_path, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to rounds_path, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:title, :description, :type_id, :image, :competition_id, :rating_type, :repeats, :minutes, :seconds, :start_prize, :peak_prize, :prize_percent, :text_prize, round_tasks_attributes: [:id, :title, :_destroy])
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_action_buttons.html.slim
- if current_user && @round_user && !@winner_user_enabled
  / = f.hidden_field :user_id, :class => 'form-control', value: current_user.id
  - if @round_video_sent
    h6.text-success Вы уже отправили видео на проверку!
  - elsif !@winner_user_enabled
    = render 'send_video_button'

- elsif current_user && !@winner_user_enabled
  - team_category = Type.find_by_is_team(true)
  - if @cant_register_solo && !team_category.nil? && @round.type_id != team_category.id
    h6.text-danger Вы не можете зарегистрироваться в данном соревновании, так как уже участвуете в одном индивидуальном комплексе!
  - else
    / = form_for current_user.round_users.new, html: { class: "form form-horizontal round_user" }, remote: true do |f|
      / = f.hidden_field :round_id, :class => 'form-control', value: @round.id
      / = f.submit "Участвовать", :class => 'btn btn-primary'
    button.btn.btn-primary.btn-payment
      | Оплатить участие
      iframe.make-payment-btn[frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/small.xml?account=410012692910825&quickpay=small&any-card-payment-type=on&button-text=02&button-size=l&button-color=black&targets=Взнос%20участника%20соревнования%20#{@round.title}&default-sum=#{@round.type.price}&label=#{current_user.id}-#{@round.id}&successURL=#{request.env['PATH_INFO']}"]

- if @winner_user_enabled && @can_send_video && @round.competition.is_active?
  = render 'send_video_button'

- if current_user && defined?(video_capturing_btn) && video_capturing_btn
  br
  br
  = render '/help/video_capturing'

app/views/rounds/_form.html.slim
= form_for @round, html: { class: "form form-horizontal round", multipart: true } do |f|
  .form-group
    = f.label :title, "Название", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    = f.error_span(:title)
  .form-group
    = f.label :description, "Описание",  :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, :class => 'form-control'
    = f.error_span(:description)
  .form-group
    = f.label :type_id, "Категория", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select(:type_id, Type.all.map{ |t| [t.title, t.id] }, {}, class: "form-control")
    = f.error_span(:type_id)
  .form-group
    = f.label :type_id, "Соревновние", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select(:competition_id, Competition.all.map{ |t| [t.title, t.id] }, {}, class: "form-control")
    = f.error_span(:competition_id)
  .form-group
    = f.label :rating_type, "Тип комплекса", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select(:rating_type, [['"Макс. повторения" за время', 0], ['"На время" нужное число повторений', 1]], {}, class: "form-control")
    = f.error_span(:rating_type)
  .form-group
    = f.label :repeats, "Нужное кол-во повторений", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.number_field(:repeats, step: 1)
    = f.error_span(:repeats)
  .form-group
    = f.label :minutes, "Время", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.number_field(:minutes, in: 0..60, step: 1)
      = f.number_field(:seconds, in: 0..60, step: 1)
      / = f.select(:minutes, 1..60.times{ |t| [t, t] }, {}, class: "form-control input-sm")
    = f.error_span(:minutes)
  .form-group
    = f.label :start_prize, "Стартовый призовой фонд", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.number_field(:start_prize, step: 1)
    = f.error_span(:start_prize)
  .form-group
    = f.label :text_prize, "Доп. Инфо.", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :text_prize, :class => 'form-control'
    = f.error_span(:text_prize)
  .form-group
    = f.label :peak_prize, "Максимальный призовой фонд", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.number_field(:peak_prize, step: 1)
    = f.error_span(:peak_prize)
  .form-group
    = f.label :prize_percent, "Процент в призовой фонд", :class => 'control-label col-lg-2'
    .col-lg-10
      = f.number_field(:prize_percent, step: 1)
    = f.error_span(:prize_percent)
  .form-group
    = f.label :image, "Изображение", class: "control-label col-lg-2"
    .col-lg-10
      = image_tag @round.image.url(:thumb), width: "150"
      |  (Текущая картинка)
      = f.file_field :image
  #tasks.form-group
    = f.label :tasks, "Упражнения", class: "control-label col-lg-2"
    .col-lg-10
      = f.fields_for :round_tasks do |round_task|
        = render 'round_task_fields', f: round_task
      .links
        = link_to_add_association "#{fa_icon 'plus'} Добавить упражнение".html_safe, f, :round_tasks
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit 'Сохранить', :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), rounds_path, :class => 'btn'

app/views/rounds/_round_task_fields.html.slim
.nested-fields
  .form-group
    / = f.label :title
    / br
    .input-group
      = f.text_field :title, class: "form-control input-sm"
      span.input-group-btn
        = link_to_remove_association "#{fa_icon 'ban'} Удалить".html_safe, f, class: "btn btn-danger btn-sm"

app/views/rounds/_send_video_button.html.slim
.spoiler-block
  button.btn.btn-primary.info-spoiler-btn Отправка видео
  .info-spoiler

    br

    .alert.alert-dismissible.alert-warning
      strong
        - if @round.rating_type == 0
          | Сколько повторений вы выполнили за
          strong
            =< "#{@round.minutes} минут #{@round.seconds} секунд?"
          | .
        - elsif @round.rating_type == 1
          | За какое время вы выполнили
          strong
            =<> "#{@round.repeats}"
          | повторения?

    = form_for @round_user.round_videos.new do |f|
      = f.hidden_field :round_user_id, value: @round_user.id

      - if @round.rating_type == 1
        .form-group
          label
            | Время(минуты):
          = f.text_field :minutes, class: "form-control input-sm"

        .form-group
          label
            | Время(секунды):
          = f.text_field :seconds, class: "form-control input-sm"

      - if @round.rating_type == 0
        .form-group
          label
            | Количество повторений:
          = f.text_field :repeats, class: "form-control input-sm"
      .form-group
        label
          | Введите ссылку на видео с YouTube:
          span[style="font-size: 10px;"]
            br
            | Примеры ссылок:
            br
            | "https://youtu.be/X3PreBW1Y" или "https://www.youtube.com/watch?v=X3PreBW1Y"
        = f.text_field :youtube_url, class: "form-control input-sm", placeholder: "https://youtu.be/VIDEO_ID"
        / input.form-control.input-sm[type="text"]
      button.btn.btn-success[type="submit"]
        | Отправить

app/views/rounds/_timer.html.slim
.winner-block
  .winner-text.winner-header.text-center
    strong Лидер будет известен через:

  .winner-text.winner-timer.text-center
    strong#timer
    / = abort @end_date.inspect
    javascript:
      var currentDate = new Date();
      var endDate = new Date("#{@end_date.year}", "#{@end_date.month - 1}", "#{@end_date.day}", 23, 59, 59, 0);
      var milliseconds = endDate.getTime() - currentDate.getTime();
      //$('#timer').html(endDate.getDate() + " " + currentDate.getDate());
      setInterval(function(){
        console.log(endDate);
        console.log(currentDate);
        x = milliseconds / 1000;
        seconds = Math.floor(x % 60);
        x /= 60;
        minutes = Math.floor(x % 60);
        x /= 60;
        hours = Math.floor(x % 24);
        x /= 24;
        days = Math.floor(x);


        if (x > 0) {
          $('#timer').html(
          '<span class="timer-seconds timer-time">' + days + '</span>' + ((days == 1) ? " день " : " дней ") +
          '<span class="timer-seconds timer-time">' + hours + "</span> часов " + '<span class="timer-seconds timer-time">' + minutes + "</span> минут" +
          '<p class="timer-seconds"><span class="timer-seconds timer-time">' + seconds + '</span> секунд</p>'
          );
          milliseconds -= 1000;
        }
      }, 1000);

  .text-center
    - if @archive_round
      | Он получил выигрыш в размере
      br
      strong>
        =<> @round.prize
        | рублей
    - else
      | Он получит выигрыш в размере
      br
      strong>[style="font-size: 20px;"]
        =<> @round.prize
        | рублей

app/views/rounds/_winner_user.html.slim
.winner-block
  .winner-text.winner-header.text-center
    - if @archive_round || !@round.competition.is_active?
      | Победитель
    - else
      | Лидер

    | &nbspэтой Zарубы:

  .winner-text.winner-name.text-center
    strong
      = @winner_round_video.round_user.user.fname
      =< @winner_round_video.round_user.user.lname
    br
    = @winner_round_video.round_user.user.email

  .winner-photo
    = image_tag @winner_round_video.round_user.user.avatar.url(:medium), width: "100%"

  .winner-text.text-center
    - if @archive_round
      | Он получил выигрыш в размере
      br
      strong>
        =<> @round.prize
        | рублей
    - else
      | Он получит выигрыш в размере
      br
      strong>
        =<> @round.prize
        | рублей
      | через:

  - unless @archive_round || !@round.competition.is_active?
    .winner-text.winner-timer.text-center
      strong#timer
      javascript:
        //var currentDate = new Date();
        //var endDate = new Date("#{@end_date.year}", "#{@end_date.month - 1}", "#{@end_date.day}", 0, 0, 0, 0);
        //var milliseconds = endDate.getTime() - currentDate.getTime();
        //$('#timer').html(endDate.getDate() + " " + currentDate.getDate());

        //console.log($(window).timerWinnerUser);

        //if (!timerWinnerUser)
        var currentDate = new Date();
        var endDate = new Date("#{@end_date.year}", "#{@end_date.month - 1}", "#{@end_date.day}", 23, 59, 59, 0);
        var milliseconds = endDate.getTime() - currentDate.getTime();

        setInterval(function(){
          console.log(endDate);
          console.log(currentDate);

          x = milliseconds / 1000;
          seconds = Math.floor(x % 60);
          x /= 60;
          minutes = Math.floor(x % 60);
          x /= 60;
          hours = Math.floor(x % 24);
          x /= 24;
          days = Math.floor(x);


          if (x > 0) {
            $('#timer').html(
            '<span class="timer-seconds timer-time">' + days + '</span>' + ((days == 1) ? " день " : " дней ") +
            '<span class="timer-seconds timer-time">' + hours + "</span> часов " + '<span class="timer-seconds timer-time">' + minutes + "</span> минут" +
            '<p class="timer-seconds"><span class="timer-seconds timer-time">' + seconds + '</span> секунд</p>'
            );
            milliseconds -= 1000;
          }
        }, 1000);

  .winner-text.winner-result.text-center
    | Время:
    strong<
      = "#{@winner_round_video.minutes}:#{@winner_round_video.seconds}"
    br
    | Повторения:
    strong<
      = @winner_round_video.repeats
  - if @archive_round
    .winner-text.winner-button-block
      a.btn.btn-primary.btn-block.btn-payment[href="#{round_video_path(@winner_round_video)}"]
        | Посмотреть видео!

  - elsif current_user && @round_user && @winner_round_video.round_user.user_id != current_user.id && @round.competition.is_active?
    .winner-text.text-center
      | Побей его результат и получи весь выигрыш вместо него!
    .winner-text.winner-button-block
      button.btn.btn-primary.btn-block.btn-payment
        | Побить рекорд!
        iframe.make-payment-btn[frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/small.xml?account=410012692910825&quickpay=small&any-card-payment-type=on&button-text=02&button-size=l&button-color=black&targets=Взнос%20участника%20соревнования%20#{@round.title}&default-sum=#{@round.type.beat_price}&label=#{current_user.id}-#{@winner_round_video.round_user.round.id}&successURL=#{request.env['PATH_INFO']}"]
    .winner-text.text-center[style="color: #aaa; font-size: 12px;"]
      = "*Стоимость пересдачи видео - #{@round.type.beat_price} руб."

app/views/rounds/archive.html.slim
- model_class = Round
.page-header
  h1
    | Архив комплексов
table.table.table-striped
  thead
    tr
      th Название
      th Категория
      th Соревнование
      th Победитель
  tbody
    - @rounds.each do |round|
      - round_videos = RoundVideo.joins(:round_user).where(round_users: { round_id: round.id })
      - winner_round_video = round_videos.order(repeats: :desc, minutes: :asc, seconds: :asc).first
      - winner_round_video = nil if round.competition.is_active?
      tr
        / td= link_to round.id, round_path(round)
        td= link_to round.title, archive_round_path(round)
        / td= round.description
        td= round.type.title
        / td=l round.created_at
        td= round.competition.blank? ? "" : "#{round.competition.id}: #{round.competition.title}"
        / td= "#{current_user.fname} #{current_user.lname}"
        td= winner_round_video ? "#{winner_round_video.round_user.user.fname} #{winner_round_video.round_user.user.lname}" : "Не определен"

app/views/rounds/archive_round.html.slim
- model_class = Round

.page-header
  h1
    .text-center
      strong
        = @round.title
      br
      | Призовой фонд:
      strong
        =<> @round.prize
      | рублей

.row
  .col-md-8.col-lg-8

    br
    .spoiler-block
      button.btn.btn-default.info-spoiler-btn Показать информацию о раунде
      .info-spoiler
        br
        p
          strong
            | Категория:
          =< @round.type.title

        p
          strong
            | Описание:
          =< @round.description
        p
          strong
            | Комплекс:
          ul.round-tasks-list
            - @round.round_tasks.each do |round_task|
              li=round_task.title

    br

    .row
      .col-lg-8.col-md-8.col-sm-8.col-xs-12
        = image_tag @round.image.url(:high), width: "100%"

    br

  - if current_user && @winner_round_video
    .col-xs-12.col-sm-4.col-md-4.col-lg-4
      = render 'winner_user'

hr

h3
  | Комментарии:

- if current_user
  = form_for(current_user.comments.new, remote: true) do |f|

    = f.hidden_field :round_id, value: @round.id

    .form-group
      = f.text_area :body, id: "comment-input-field", class: "form-control", style: "resize: vertical", placeholder: "Текст комментария.."

    .actions
      = f.submit "Отправить", class: "btn btn-success"

br

- if @round.comments.blank?
  p
    | Здесь пока еще нет комментариев.

.comments.container-fluid
  - @round.comments.each do |comment|
    = render comment


/ = link_to t('.back', :default => t("helpers.links.back")), rounds_path, :class => 'btn btn-default'
/ '
/ = link_to t('.edit', :default => t("helpers.links.edit")), edit_round_path(@round), :class => 'btn btn-default'
/ '
/ = link_to t('.destroy', :default => t("helpers.links.destroy")), round_path(@round), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/rounds/edit.html.slim
- model_class = Round
.page-header
  h1
    | Изменение комплекса
= render :partial => "form"

app/views/rounds/index.html.slim
- model_class = Round
.page-header
  h1
    | Комплексы
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th Название
      th Категория
      th Соревнование
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @rounds.each do |round|
      tr
        td= round.id
        td= round.title
        / td= round.description
        td= round.type.title
        / td=l round.created_at
        td= round.competition.blank? ? "" : "#{round.competition.id}: #{round.competition.title}"
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_round_path(round), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), round_path(round), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to 'Создать', new_round_path, :class => 'btn btn-primary'

app/views/rounds/new.html.slim
- model_class = Round
.page-header
  h1
    | Добавление комплекса
= render :partial => "form"

app/views/rounds/show.html.slim
- model_class = Round
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name("Название раунда") + ':'
  br
  = @round.title
p
  strong= model_class.human_attribute_name("Описание") + ':'
  br
  = @round.description
p
  strong= model_class.human_attribute_name("Тип") + ':'
  br
  = @round.type.title

= link_to t('.back', :default => t("helpers.links.back")), rounds_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_round_path(@round), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), round_path(@round), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/rounds/show_of_type.html.slim
- model_class = Round

.page-header
  h1
    .text-center
      strong
        = @round.title
      br
      | Призовой фонд:
      strong
        =<> @round.prize
      | рублей

      - unless @round.text_prize.blank?
        .text_prize
          br
          | Доп.информация:
          =<> @round.text_prize

.row
  .col-md-8.col-lg-8

    br
    .spoiler-block
      button.btn.btn-primary.info-spoiler-btn Показать информацию о комплексе
      '
      = link_to 'Рейтинг', ratings_path(@round.type_id), class: "btn btn-primary"
      .info-spoiler
        br
        p
          strong
            | Категория:
          br
          =< @round.type.title

        - unless @round.description.blank?
          p
            strong
              | Описание:
            br
            =< @round.description

        - unless @round_tasks.blank?
          p
            strong
              | Комплекс:
            ul.round-tasks-list
              - @round_tasks.each do |round_task|
                li=round_task.title
        p
          strong
            | Тип:
          br
          - if @round.rating_type == 0
            | Требуется выполнить максимальное количество повторений за
            strong
              =< "#{@round.minutes} минут #{@round.seconds} секунд"
            | .
          - elsif @round.rating_type == 1
            | Требуется выполнить
            strong
              =<> "#{@round.repeats}"
            | повторения за минимальное время.
    br
    = render 'action_buttons'

    - if current_user && @round_user && !@winner_user_enabled && !@round_video_sent && false
      br
      .alert.alert-dismissible.alert-danger
        strong
          p Используйте данное имя для видео, иначе оно не будет проверено!
          p = "CrossFit-Zаруба - #{@round.title} - группа #{@round.type.title}, #{current_user.fname} #{current_user.lname}"


    br
    br

    .row
      .col-lg-8.col-md-8.col-sm-8.col-xs-12
        = image_tag @round.image.url(:high), width: "100%"

    br

    / = render 'action_buttons', video_capturing_btn: true
    - if current_user
      = render '/help/video_capturing'
    / - if current_user && !@round_video_sent
    /   br
    /   .alert.alert-dismissible.alert-danger
    /     strong
    /       p Используйте данное имя для видео, иначе оно не будет проверено!
    /       p = "CrossFit-Zаруба - #{@round.title} - группа #{@round.type.title}, #{current_user.fname} #{current_user.lname}"


    / iframe#make-payment-btn[frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/small.xml?account=410012600571450&quickpay=small&any-card-payment-type=on&button-text=02&button-size=m&button-color=black&targets=Взнос%20участника%20соревнования%20#{@round.title}&default-sum=#{@round.type.price}&label=#{current_user.id}-#{@round.id}&successURL=" width="160" height="42"]

  .col-xs-12.col-sm-4.col-md-4.col-lg-4
    - if @winner_user_enabled
      - if @winner_round_video
        = render 'winner_user'
    - else
      = render 'timer'

hr

h3
  | Комментарии:

- if current_user
  = form_for(current_user.comments.new, remote: true) do |f|

    = f.hidden_field :round_id, value: @round.id

    .form-group
      = f.text_area :body, id: "comment-input-field", class: "form-control", style: "resize: vertical", placeholder: "Текст комментария.."

    .actions
      = f.submit "Отправить", class: "btn btn-success"

br

- if @comments.blank?
  p
    | Здесь пока еще нет комментариев.

.comments.container-fluid
  - @comments.each do |comment|
    = render comment