config/routes.rb
Rails.application.routes.draw do
  resources :ads
  resources :competitions
  resources :round_video_ratings
  resources :round_videos
  resources :round_tasks
  resources :comments
  resources :round_users
  resources :rounds
  resources :types

  get '/rounds/type/:type_id' => 'rounds#show_of_type', as: :show_of_type
  get '/round_videos/list/:round_id' => 'round_videos#list', as: :round_video_list
  get '/rounds/rating/:round_id' => 'round_videos#rating', as: :rating_round_video
  get '/categories' => 'types#block_list', as: :categories
  get '/ratings/:type_id' => 'round_video_ratings#list', as: :ratings
  get '/archive' => 'rounds#archive', as: :archive
  get '/archive/:round_id' => 'rounds#archive_round', as: :archive_round

  get '/round_users_payment' => 'round_users#payment'
  post '/round_users_payment' => 'round_users#payment'

  get '/how_to' => 'help#how_to', as: :how_to
  get '/about' => 'help#about', as: :about
  get '/contacts' => 'help#contacts', as: :contacts
  get '/download_reglament' => 'help#download_reglament', as: :download_reglament

  get '/admin' => 'help#admin_panel', as: :admin_panel
  get '/prize' => 'help#prize_panel', as: :prize_panel
  get '/users' => 'help#user_list', as: :user_list

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root "types#block_list"

  get '/image_crop' => 'help#image_crop', as: :image_crop
  get '/avatar_with_frame' => 'help#avatar_with_frame', as: :avatar_with_frame
  get '/avatar_with_frame_download' => 'help#avatar_with_frame_download', as: :avatar_with_frame_download

end

app/views/layouts/_footer.html.slim
footer.text-center
  p
    | &copy;
    a[href="http://clienddev.ru"]
      |  ClienDDev
    |  2015

app/views/layouts/_navbar.html.slim
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[data-toggle="collapse" data-target=".navbar-responsive-collapse"]
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand[href="#{root_path}"]
        | CrossFit online Zаруба
    .navbar-collapse.collapse.navbar-responsive-collapse
      .text-center.hidden-sm.hidden-xs[style="position: absolute; width: 30%; left: 35%; color: #fff; font-size: 15px; margin-top: 12px;"]
        strong Деньги за победу
      ul.nav.navbar-nav.navbar-right
        li= link_to "Контакты", contacts_path
        li= link_to "Регламент", download_reglament_path
        li= link_to "О Проекте", about_path
        - if current_user
          li= link_to "Выход", destroy_user_session_path, method: :delete

app/views/layouts/_sidebar.html.slim
.well.sidebar-nav.content-wrap
  - if current_user
    h3.text-center[style="margin-top:10px;"]= "#{current_user.fname} #{current_user.lname}"
    / = image_tag current_user.avatar.url(:medium), style: "width: 100%;"
    .user-avatar
      - unless cookies[:avatar_downloaded] == 'true'
        a[href="#{avatar_with_frame_download_path}"]
          .social-text.text-center
            | Выложи это фото у себя в социальной сети!
            br
            br
            .social-icons
              => fa_icon "vk 2x"
              => fa_icon "facebook 2x"
              => fa_icon "twitter 2x"
              => fa_icon "instagram 2x"
            br
            .social-text-small Кликни, чтобы скачать фото
            javascript:
              $('.social-text').on('click', function(){
                $(this).fadeOut(100);
              });

      = image_tag "#{avatar_with_frame_path}", style: "width: 100%;"
  - else
    h3.text-center Пожалуйста, авторизуйтесь
    = image_tag "medium/missing_avatar.png", style: "width: 100%;"
  ul.nav.nav-list
    - if current_user
      li= link_to "Профиль", edit_user_registration_path(current_user)
      li= link_to "Рейтинг", ratings_path(Type.third)
    - else
      li= link_to "Вход", new_user_session_path
      li= link_to "Регистрация", new_user_registration_path
    li= link_to "Категории", categories_path
    li= link_to "Архив Zаруб", archive_path
    li= link_to "Как принять участие", how_to_path
    - if current_user && current_user.is_admin?
      li= link_to "Панель Судьи", admin_panel_path

- ads = getAds(4)
- if ads.count > 0
  .well.sidebar-nav.content-wrap
    ul.nav.nav-list.text-center[style="margin-left: 0;"]
      - ads.each do |ad|
        li
          a[href="http://#{ad.site}" type="button" data-toggle="tooltip" data-placement="top" title="" data-original-title="#{ad.description}" style="padding: 0px;"]
            - if ad.use_image
              .rek-el-image
                - if ad.is_big_picture
                  = image_tag ad.image.url(:medium)
                - else
                  = image_tag ad.image.url(:thumb)
            -else
              .rek-el-text
                = ad.title

- partners = getPartners(4)
- if partners.count > 0
  .well.sidebar-nav.content-wrap
    ul.nav.nav-list.text-center[style="margin-left: 0;"]
      - partners.each do |ad|
        li
          a[href="http://#{ad.site}" type="button" data-toggle="tooltip" data-placement="top" title="" data-original-title="#{ad.description}" style="padding: 0px;"]
            - if ad.use_image
              .rek-el-image
                - if ad.is_big_picture
                  = image_tag ad.image.url(:medium)
                - else
                  = image_tag ad.image.url(:thumb)
            -else
              .rek-el-text
                = ad.title

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Zaruba"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    link[href='https://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css']
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.jpg', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    = render 'layouts/navbar'

    .container
      .row
        .com-sm-3.col-md-3.col-lg-3
          = render 'layouts/sidebar'
        .com-sm-9.col-md-9.col-lg-9
          .row
            .col-md-12
              - if @need_round_types
                .types.btn-group.btn-group-justified
                  - @competition = Competition.current
                  - Type.all.order(id: :asc).each do |type|
                    - round = @competition.rounds.select { |r| r.type_id == type.id }.first unless @competition.nil?
                    = link_to "<strong>#{type.title}</strong><br/><strong>#{round ? round.prize : 0}</strong> рублей".html_safe, show_of_type_path(type), class: "btn btn-default", style: "#{@round.type_id == type.id ? 'background-color: #ccc' : ''}"
              - elsif @need_rating_types
                .types.btn-group.btn-group-justified
                  - Type.all.order(id: :asc).each do |type|
                    = link_to "<strong>#{type.title}</strong>".html_safe, ratings_path(type), class: "btn btn-default", style: "#{@round.type_id == type.id ? 'background-color: #ccc' : ''}"
          / = bootstrap_flash
          - if @no_background
            .content-wrap-nopad
              = yield
          - else
            .content-wrap
              = yield

      = render 'layouts/footer'

  javascript:
    readyFunction();

app/views/layouts/devise.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Zaruba"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    link[href='https://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css']
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.jpg', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    = render 'layouts/navbar'

    .container
      .row
        .col-lg-3
          = render 'layouts/sidebar'
        .col-lg-9
          / = bootstrap_flash
          - if @no_background
            .content-wrap-nobg
              = yield
          - else
            .content-wrap
              = yield

      = render 'layouts/footer'

app/views/layouts/devise_.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Zaruba"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    = render 'layouts/navbar'

    .container
      .row
        .col-lg-6.col-md-offset-3
          / = bootstrap_flash
          .content-wrap
            = yield
        / .col-lg-3
        /   .well.sidebar-nav
        /     h3 Sidebar
        /     ul.nav.nav-list
        /       li.nav-header Sidebar
        /       li= link_to "Link 1", "/path1"
        /       li= link_to "Link 2", "/path2"
        /       li= link_to "Link 3", "/path3"

      = render 'layouts/footer'